const { DB } = require("./config");
const { Pool } = require("pg");

const createBooks = `CREATE TABLE IF NOT EXISTS books (
    book_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    book_name VARCHAR(100) NULL,
    summary VARCHAR(450) NULL,
    author VARCHAR(60) NULL,
    isbn  VARCHAR(60) NULL,
    publishing_year DATE NULL,
    genre VARCHAR(60) NULL,
    image VARCHAR(512) NULL,
  	rating DECIMAL(5,1) NULL,
   	user_id INT  NULL,
    PRIMARY KEY (book_id),
    FOREIGN KEY (user_id) REFERENCES user_tb(id));`;
const insertBooks = `INSERT INTO books (book_name,summary,author,isbn,publishing_year,genre,image,rating,user_id)
VALUES
  ('Convenience Store','On his first ever graveyard shift at the local convenience store, Haru Muramatsu has to contend with a genuine, albeit out-of-touch, demon lord. ','Gaia & Macozi','E5C55B5B-4B41-548E-8FB9-27486BDA05A1','Apr 10, 2021','Comedy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646186827/Novel-app/Its-My-First-Time-Working-Late-Nights-at-a-Convenience-Store-and-If-I-Keep-Getting-Demon-Lords-Kappa-and-Other-Oddballs-as-Customers-Im-Giving-My-TwoWeeks-Notice-333x500_pbdfr2.png',4.1,null),
  ('Black Bullet','Rentaro is still a fugitive, running from the law for a murder he didnt commit','Shiden Kanzaki','45BB4E1A-3186-0811-D59B-CEA83CC45AA8','Oct 3, 2022','Dystopian','https://res.cloudinary.com/djnvkwbme/image/upload/v1646186816/Novel-app/48eb589a1ed07f8bb5daf4c746b2d9aa_eplq9j.jpg',3.3,null),
  ('The Faraway Paladin','Born into a new world after a life of stagnancy, Will awakens to the faces of a skeleton, a ghost, and a mummy.',' Kanata Yanagino','C6A28657-07D9-C712-20E2-A1D2666E42EC','Dec 26, 2022','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646186809/Novel-app/paladin2_cover_400_vndwa8.jpg',5.0,null),
  ('The Rising of the Shield Hero','Naofumi Iwatani, an otaku, becomes cursed with the fate of being the "Shield Hero."','Aneko Yusagi','BEE821A6-C169-1641-C0EF-4A4864C1322A','Apr 19, 2021','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646186771/Novel-app/LN_Vol_1_ENG_oziau0.jpg',2.1,null),
  ('Black Clover','In a world where magic is everything, Asta and Yuno are both found abandoned at a church on the same day.','Shueisha','E7073C91-74C3-B38C-E992-278C48992ADD','Apr 8, 2022','Sci-Fi','https://res.cloudinary.com/djnvkwbme/image/upload/v1646187515/Novel-app/download_rbzkru.jpg',4.8,null),
  ('Overlord','After announcing it will be discontinuing all service, the internet game ‘Yggdrasil’ shut down…','Kugane Maruyama','49725D94-B3AE-9419-30A6-3D44CBB71EFD','Jan 2, 2022','Thriller','https://res.cloudinary.com/djnvkwbme/image/upload/v1646187653/Novel-app/Overlord_poster_tueqcc.jpg',3.5,null),
  ('Warlock of the Magus World','When a futuristic scientist is transported into the body of a young man in a fantasy world, his curiosity and desire for power push him to pursue magic.','Wen Chao Gong','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Action','https://res.cloudinary.com/djnvkwbme/image/upload/v1646188173/Novel-app/Ancient_god_of_death_jstprv.jpg',3.8,null),
('The Strange Adventure of a Broke Mercenary','A gritty swords and sorcery tale of a veteran mercenary who must start anew after he loses his old company','Mine','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646188309/Novel-app/8125gVxFB6L_loz5sq.jpg',3.8,null),
('The Wise Mans Fear','There are three things all wise men fear: the sea in storm, a night with no moon, and the anger of a gentle man','patrick rothfuss','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646188472/Novel-app/81NX-69L22L_wn4kjs.jpg',3.8,null),
('The Way of Kings','Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike','Brandon Sanderson','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646188586/Novel-app/b94c84eb27af5643db7224def286fb0f_original_oo6m4l.jpg',3.8,null),
('A Quest of Heroes','The youngest of four, the least favorite of his father, Thorgrin comes to learn he has mysterious powers he does not understand, that he has a special gift, and a special destiny.','Morgan Rice','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646188790/Novel-app/41cSQ9zY5yL_aar42d.jpg',3.8,null),
('The Inquisition','A year has passed since the Tournament. Fletcher and Ignatius have been locked away in Pelts dungeons, but now they must face trial at the hands of the Inquisition','Taran Matharu','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Fantasy','https://res.cloudinary.com/djnvkwbme/image/upload/v1646188953/Novel-app/91645p-C_RL_eh1m3v.jpg',3.8,null)
`;

const start = async () => {
  try {
    const pool = new Pool({
      user: DB.PGUSER,
      host: DB.PGHOST,
      database: DB.PGDATABASE,
      password: DB.PGPASSWORD,
      port: DB.PGPORT,
    });
    const start = Date.now();
    await pool.connect();
    await pool.query(createBooks);
    await pool.query(insertBooks);

    const duration = Date.now() - start;
    console.log({ msg: "executed query", duration });
    await pool.end();
  } catch (error) {
    console.log({ msg: "Database could not be setup", error });
    await pool.end();
  }
};

start();
